version: "3.9"

services:
  db:
    image: postgres:15.1-alpine
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - pgdata-book-space:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    networks:
      - backend
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy

  api-auth:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
      target: dev
    image: api-auth
    container_name: api-auth
    restart: unless-stopped
    env_file:
      - .env
      - ./auth_service/.env
    ports:
      - "5000:5000"
    volumes:
      - ./auth_service/src:/usr/src/app/src
      - /usr/src/app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health/db"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

  api-book:
    build:
      context: ./book_service
      dockerfile: Dockerfile
      target: dev
    image: api-book
    container_name: api-book
    restart: unless-stopped
    env_file:
      - .env
      - ./book_service/.env
    ports:
      - "4000:4000"
    volumes:
      - ./book_service/src:/usr/src/app/src
      - /usr/src/app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

volumes:
  pgdata-book-space:

networks:
  backend:
    driver: bridge
